import {useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {api,human,message} from '../lib/api'
import {useApp,useData} from '../lib/context'
import {modules} from '../lib/modules'
import {Modal,Field,Submit} from './ui'
export function ReferenceInput({field,value,onChange,disabled}){
 const [search,setSearch]=useState(''),query=useData(`/${field.source}`,{limit:200,...(search?{q:search}:{})})
 const multiple=field.name.endsWith('Ids')
 return <div><input aria-label={`Search ${field.label}`} placeholder={`Search ${field.label.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)} className="mb-1 py-1.5 text-xs" disabled={disabled}/><select required={field.required} multiple={multiple} size={multiple?4:undefined} disabled={disabled||query.isPending} value={value||(multiple?[]:'')} onChange={e=>onChange(multiple?Array.from(e.target.selectedOptions,o=>o.value):e.target.value)}>{!multiple&&<option value="">{query.isPending?'Loading…':`Choose ${field.label.toLowerCase()}`}</option>}{query.data?.data?.map(row=><option key={row.id} value={row.id}>{row.name||row.key}{row.sku?` · ${row.sku}`:''}</option>)}</select>{multiple&&<p className="mt-1 text-[10px] text-slate-400">Use Ctrl / Cmd to select multiple options.</p>}{query.error&&<p className="mt-1 text-xs text-red-600">{message(query.error)}</p>}</div>
}
export default function RecordForm({module,record,onClose}){
 const config={...modules[module],fields:[...modules[module].fields,...(record && Object.hasOwn(record,"active")?[{name:"active",label:"Active record (clear to archive)",type:"checkbox"}]:[])]},{notify}=useApp(),client=useQueryClient()
 const [values,setValues]=useState(()=>Object.fromEntries(config.fields.map(f=>[f.name,record?.[f.name]??f.default??(f.name.endsWith('Ids')?[]:f.type==='checkbox'?false:'')]))),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const change=(name,value)=>setValues(v=>({...v,[name]:value}))
 async function submit(e){e.preventDefault();setError('');setBusy(true);try{
  const payload={};for(const field of config.fields){const value=values[field.name];if(value===''&&!field.required)continue;payload[field.name]=field.type==='number'?Number(value):value}
  if(record){const proposedData={};for(const [key,value] of Object.entries(payload))if(!['locationId','userId'].includes(key)&&String(value)!==String(record[key]??''))proposedData[key]=value;await api.post(`/${module}/${record.id}/corrections`,{reason,proposedData})}else await api.post(`/${module}`,payload)
  await client.invalidateQueries();notify(record?'Correction submitted for approval. Original record is unchanged.':module==='expenses'?'Expense recorded and submitted for approval.':'Record created.');onClose()
 }catch(err){setError(message(err))}finally{setBusy(false)}}
 return <Modal title={record?`Request ${config.singular} correction`:`New ${config.singular}`} description={record?'Protected changes take effect only after an independent review.':'Fields marked with * are required.'} onClose={onClose}><form onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2">{config.fields.map(field=><div key={field.name} className={field.type==='textarea'||field.name.endsWith('Ids')?'sm:col-span-2':''}><Field label={field.label} required={field.required}>{field.source?<ReferenceInput field={field} value={values[field.name]} onChange={v=>change(field.name,v)} disabled={!!record&&['locationId','userId'].includes(field.name)}/>:field.type==='select'?<select value={values[field.name]} onChange={e=>change(field.name,e.target.value)}>{field.options.map(o=><option key={o} value={o}>{human(o)}</option>)}</select>:field.type==='textarea'?<textarea rows={3} value={values[field.name]} onChange={e=>change(field.name,e.target.value)}/>:field.type==='checkbox'?<input type="checkbox" checked={values[field.name]} onChange={e=>change(field.name,e.target.checked)}/>:<input type={field.type} required={field.required} minLength={field.minLength} maxLength={field.type==='password'?128:255} min={field.min??(field.type==='number'?0:undefined)} step={field.step} value={values[field.name]} onChange={e=>change(field.name,e.target.value)} autoComplete={field.type==='password'?'new-password':undefined}/>}</Field></div>)}</div>{record&&<div className="mt-5"><Field label="Reason for correction" required><textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000} required rows={3}/></Field></div>}{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><Submit busy={busy}>{record?'Submit correction':'Create record'}</Submit></div></form></Modal>
}

