import {useEffect,useRef} from 'react'
import {AlertCircle,Inbox,ChevronLeft,ChevronRight,X,LoaderCircle} from 'lucide-react'
import {human,message} from '../lib/api'
export function Badge({value}){const good=['healthy','active','approved','confirmed','synced','received','completed'].includes(value),bad=['critical','failed','rejected','conflict','inactive'].includes(value);return <span className={`inline-flex items-center gap-1.5 whitespace-nowrap rounded-md px-2 py-1 text-[11px] font-medium capitalize ${good?'bg-emerald-50 text-emerald-700':bad?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{human(value||'pending')}</span>}
export function Empty({title='No records yet',description='Records will appear here as your team starts working.',action}){return <div className="flex flex-col items-center px-6 py-16 text-center"><div className="mb-4 rounded-2xl bg-slate-50 p-4 text-slate-400"><Inbox size={26}/></div><h3 className="font-semibold text-slate-700">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">{description}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function ErrorState({error,retry}){return <div role="alert" className="card flex flex-col items-center gap-4 p-10 text-center"><AlertCircle className="text-red-500"/><p className="max-w-lg text-sm text-slate-600">{message(error)}</p>{retry&&<button className="btn-secondary" onClick={retry}>Try again</button>}</div>}
export function Skeleton(){return <div aria-label="Loading" role="status" className="space-y-4 animate-pulse"><div className="h-10 w-1/3 rounded-lg bg-slate-200/70"/><div className="grid grid-cols-2 gap-5 xl:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="card h-32 bg-slate-100"/>)}</div><div className="card h-80 bg-slate-100"/></div>}
export function PageHeader({eyebrow='WORKSPACE',title,description,children}){return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-2">{eyebrow}</p><h1 className="text-[27px] font-semibold tracking-[-.8px] text-slate-900">{title}</h1>{description&&<p className="mt-1.5 text-[13px] text-slate-500">{description}</p>}</div><div className="flex flex-wrap gap-2">{children}</div></div>}
export function Modal({title,description,onClose,children}){const ref=useRef(null);useEffect(()=>{const dialog=ref.current;dialog.showModal();return()=>dialog.close()},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}} className="m-auto max-h-[90dvh] w-[calc(100%-2rem)] max-w-2xl overflow-y-auto rounded-2xl border-0 bg-white p-0 shadow-2xl backdrop:bg-slate-900/45"><div className="sticky top-0 z-10 flex items-start justify-between border-b border-slate-100 bg-white px-6 py-5"><div><h2 className="text-lg font-semibold">{title}</h2>{description&&<p className="mt-1 text-xs text-slate-500">{description}</p>}</div><button aria-label="Close dialog" className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="p-6">{children}</div></dialog>}
export function Field({label,children,required}){return <label className="block"><span className="field-label">{label}{required&&<span aria-hidden="true" className="ml-1 text-brand-600">*</span>}</span>{children}</label>}
export function Submit({busy,children='Save record'}){return <button type="submit" className="btn" disabled={busy}>{busy&&<LoaderCircle size={15} className="animate-spin"/>}{children}</button>}
export function Table({columns,rows=[],emptyTitle,page=1,total=0,limit=25,onPage,onRow}){return <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50/80"><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||index} className={onRow?'cursor-pointer':''} onClick={()=>onRow?.(row)}>{columns.map(c=><td key={c.key}>{c.render?c.render(row):String(row[c.key]??'—')}</td>)}</tr>)}</tbody></table></div>{!rows.length&&<Empty title={emptyTitle}/>}<div className="flex items-center justify-between gap-4 border-t border-slate-100 px-5 py-4 text-xs text-slate-500"><span>{total?`${(page-1)*limit+1}–${Math.min(page*limit,total)} of ${total} records`:'0 records'}</span>{onPage&&<div className="flex items-center gap-3"><button aria-label="Previous page" className="icon-btn" disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft size={16}/></button><span>Page {page}</span><button aria-label="Next page" className="icon-btn" disabled={page*limit>=total} onClick={()=>onPage(page+1)}><ChevronRight size={16}/></button></div>}</div></div>}
