import {money,number,date} from './api'
const f=(name,label,type='text',extra={})=>({name,label,type,...extra})
const ref=(name,label,source,required=true)=>f(name,label,'select',{source,required})
const col=(key,label,format)=>({key,label,...(format?{render:r=>format(r[key])}:{})})
const active={key:'active',label:'Status',badge:true}
export const modules={
 products:{title:'Products',singular:'product',description:'Your product catalog, pricing, and stock thresholds.',permission:'products.read',write:'products.manage',columns:[col('name','Product'),col('sku','SKU'),col('unit','Unit'),col('costPrice','Cost price',money),col('sellingPrice','Selling price',money),col('minimumStock','Min. stock',number),active],fields:[f('name','Product name','text',{required:true}),f('sku','SKU','text',{required:true}),f('barcode','Barcode'),ref('categoryId','Category','product-categories',false),f('unit','Unit (e.g. carton, piece, kg)','text',{required:true}),f('costPrice','Cost price (₦)','number',{required:true,step:'0.01',default:0}),f('sellingPrice','Selling price (₦)','number',{required:true,step:'0.01',default:0}),f('minimumStock','Minimum stock','number',{required:true,step:'0.001',default:0}),f('description','Description','textarea')]},
 locations:{title:'Locations',singular:'location',description:'Manage branches and distribution locations across Nigeria.',permission:'locations.read',write:'locations.manage',columns:[col('name','Location'),col('state','State'),col('city','City'),col('kind','Type'),active],fields:[f('name','Location name','text',{required:true}),f('state','State / FCT','text',{required:true}),f('city','City','text',{required:true}),f('kind','Location type','select',{options:['branch','distribution','head_office'],default:'branch'}),f('address','Address','textarea')]},
 warehouses:{title:'Warehouses',singular:'warehouse',description:'Storage facilities and their assigned branches.',permission:'locations.read',write:'locations.manage',columns:[col('name','Warehouse'),col('code','Code'),col('locationId','Location'),col('address','Address'),active],fields:[f('name','Warehouse name','text',{required:true}),f('code','Warehouse code','text',{required:true}),ref('locationId','Location','locations'),f('address','Address','textarea')]},
 expenses:{title:'Expenses',singular:'expense',description:'Track operational spending and financial approvals.',permission:'finance.read',write:'expenses.write',columns:[col('number','Expense number'),col('description','Description'),col('amount','Amount',money),col('expenseDate','Expense date',date),col('paymentMethod','Payment method'),{key:'status',label:'Approval',badge:true}],fields:[ref('categoryId','Category','expense-categories'),f('description','Description','text',{required:true}),f('amount','Amount (₦)','number',{required:true,step:'0.01',min:0.01}),ref('locationId','Location','locations'),ref('warehouseId','Warehouse','warehouses',false),f('department','Department'),f('paymentMethod','Payment method','select',{options:['bank_transfer','cash','card','cheque'],default:'bank_transfer'}),f('expenseDate','Expense date','date',{required:true,default:new Date().toISOString().slice(0,10)}),f('reference','Payment reference'),f('receiptUrl','Receipt link (HTTPS)','url')]},
 distributors:{title:'Distributors',singular:'distributor',description:'Distribution partners, accounts, and locations.',permission:'distributors.read',write:'distributors.manage',columns:[col('name','Distributor'),col('phone','Phone'),col('locationId','Location'),col('address','Address'),active],fields:[f('name','Distributor name','text',{required:true}),f('phone','Phone number','tel'),ref('locationId','Location','locations'),ref('userId','Linked distributor account','users',false),f('address','Address','textarea')]},
 incoming:{title:'Incoming goods',singular:'receipt',description:'Every delivery received, recorded, and accounted for.',permission:'inventory.read',write:'inventory.write',movement:'incoming'},outgoing:{title:'Outgoing goods',singular:'dispatch',description:'Dispatch stock with availability checks and a complete trail.',permission:'inventory.read',write:'inventory.write',movement:'outgoing'},movements:{title:'Stock movements',singular:'movement',description:'The complete history of stock entering, leaving, and moving.',permission:'inventory.read',write:'inventory.write',movement:'incoming'},
 inventory:{title:'Inventory',singular:'movement',description:'A live view of available, reserved, and damaged stock.',permission:'inventory.read',write:'inventory.write',movement:'incoming',columns:[{key:'product',label:'Product',render:r=>r.product?.name}, {key:'sku',label:'SKU',render:r=>r.product?.sku},{key:'warehouse',label:'Warehouse',render:r=>r.warehouse?.name},col('quantity','On hand',number),col('available','Available',number),col('reserved','Reserved',number),col('damaged','Damaged',number),col('version','Version')]},
 transfers:{title:'Warehouse transfers',singular:'transfer',description:'Move stock safely from request to destination receipt.',permission:'inventory.read',write:'inventory.write',columns:[col('number','Transfer reference'),col('productId','Product'),col('sourceWarehouseId','From'),col('destinationWarehouseId','To'),col('quantity','Quantity',number),{key:'status',label:'Status',badge:true}],fields:[ref('productId','Product','products'),ref('sourceWarehouseId','Source warehouse','warehouses'),ref('destinationWarehouseId','Destination warehouse','warehouses'),f('quantity','Quantity','number',{required:true,step:'0.001',min:0.001}),f('notes','Notes','textarea')]},
 users:{title:'Team & access',singular:'team member',description:'Give every person the right role and location access.',permission:'users.manage',write:'users.manage',columns:[col('name','Name'),col('email','Email'),{key:'roles',label:'Roles',render:r=>r.roles?.map(v=>v.name).join(', ')},{key:'locations',label:'Locations',render:r=>r.locations?.map(v=>v.name).join(', ')||'—'},active],fields:[f('name','Full name','text',{required:true}),f('email','Email','email',{required:true}),f('password','Initial password (12+ characters)','password',{required:true,minLength:12}),ref('roleIds','Roles','roles'),ref('locationIds','Assigned locations','locations',false)]},
 roles:{title:'Roles & permissions',singular:'role',description:'Create reusable access rules for your team.',permission:'users.manage',write:'users.manage',columns:[col('name','Role'),{key:'organizationWide',label:'Scope',render:r=>r.organizationWide?'Organization-wide':'Assigned locations'},{key:'permissions',label:'Permissions',render:r=>r.permissions?.map(p=>p.key).join(', ')}],fields:[f('name','Role name','text',{required:true}),f('organizationWide','Organization-wide visibility','checkbox'),ref('permissionIds','Permissions','permissions',false)]},
 'product-categories':{title:'Product categories',singular:'category',description:'Organize your catalog with configurable categories.',permission:'products.read',write:'products.manage',columns:[col('name','Category'),col('createdAt','Created',date)],fields:[f('name','Category name','text',{required:true})]},
 'expense-categories':{title:'Expense categories',singular:'category',description:'Organize spending with your company’s own categories.',permission:'finance.read',write:'expenses.write',columns:[col('name','Category'),col('createdAt','Created',date)],fields:[f('name','Category name','text',{required:true})]},
 audit:{title:'Audit trail',description:'An accountable history of important business actions.',permission:'audit.read',columns:[col('createdAt','Time',date),col('action','Action'),col('module','Module'),col('userId','User'),col('recordId','Record'),col('ip','IP address')]}
}
for(const key of ['incoming','outgoing','movements'])modules[key].columns=[col('number','Reference'),{key:'product',label:'Product',render:r=>r.product?.name},{key:'warehouse',label:'Warehouse',render:r=>r.warehouse?.name},col('type','Type'),col('quantity','Quantity',number),col('occurredAt','Date',date),{key:'status',label:'Status',badge:true}]
for(const key of ['incoming','outgoing','movements'])modules[key].fields=[f('reference','Reference'),f('counterparty','Supplier / customer'),f('delivery','Delivery information','textarea'),f('notes','Notes','textarea')]
modules.transfers.fields.find(field=>field.name==='destinationWarehouseId').source='transfer-destinations'
