import {useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'

import {useApp,useData} from '../lib/context'
import {api,date,human,message} from '../lib/api'
import {PageHeader,Skeleton,ErrorState,Table,Badge,Modal,Field,Submit} from '../components/ui'
export default function Approvals(){
 const {user,can,notify}=useApp(),client=useQueryClient(),[status,setStatus]=useState('pending'),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[decision,setDecision]=useState('approved'),[comments,setComments]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const query=useData('/approvals',{status,page})
 async function review(e){e.preventDefault();setBusy(true);setError('');try{await api.post(`/approvals/${selected.id}/review`,{decision,comments});await client.invalidateQueries();notify(`Request ${decision}.`);setSelected(null);setComments('')}catch(err){setError(message(err))}finally{setBusy(false)}}
 const columns=[{key:'type',label:'Request',render:r=><div><p className="font-medium capitalize">{human(r.type)}</p><p className="mt-1 text-[10px] text-slate-400">{r.id.slice(0,8).toUpperCase()}</p></div>},{key:'module',label:'Module',render:r=><span className="capitalize">{r.module}</span>},{key:'reason',label:'Reason'},{key:'createdAt',label:'Requested',render:r=>date(r.createdAt)},{key:'status',label:'Status',render:r=><Badge value={r.status}/>},{key:'action',label:'',render:r=><button className="text-xs font-medium text-brand-700" onClick={()=>{setSelected(r);setError('')}}>Review details</button>}]
 return <><PageHeader eyebrow="GOVERNANCE" title="Approvals" description="Review the changes. Understand the reason. Keep every decision accountable."/><div className="mb-5 flex gap-1 rounded-lg border border-slate-200 bg-white p-1 sm:w-fit">{['pending','approved','rejected','cancelled'].map(s=><button key={s} className={`flex-1 rounded-md px-4 py-2 text-xs capitalize ${status===s?'bg-brand-50 font-semibold text-brand-700':'text-slate-500'}`} onClick={()=>{setStatus(s);setPage(1)}}>{s}</button>)}</div>{query.isPending?<Skeleton/>:query.error?<ErrorState error={query.error} retry={query.refetch}/>:<Table columns={columns} rows={query.data.data} total={query.data.total} page={page} onPage={setPage} emptyTitle={`No ${status} approval requests`}/>}
 {selected&&<Modal title="Review change request" description={`${human(selected.type)} · ${selected.module}`} onClose={()=>setSelected(null)}><div className="mb-5 flex items-center justify-between"><Badge value={selected.status}/><span className="text-xs text-slate-400">{date(selected.createdAt)}</span></div><div className="mb-5 rounded-lg bg-slate-50 p-4"><p className="eyebrow">REASON FOR REQUEST</p><p className="mt-2 text-sm leading-6">{selected.reason}</p><p className="mt-3 break-all text-[11px] text-slate-400">Requested by: {selected.requestedBy}<br/>Affected record: {selected.recordId}</p></div><div className="overflow-x-auto rounded-lg border border-slate-200"><table className="w-full"><thead className="bg-slate-50"><tr><th>Field</th><th>Original value</th><th>Proposed value</th></tr></thead><tbody>{Object.entries(selected.proposedData).map(([key,value])=><tr key={key}><td className="font-medium">{human(key)}</td><td className="text-slate-400">{String(selected.originalData[key]??'—')}</td><td className="font-medium text-brand-700">{String(value??'—')}</td></tr>)}</tbody></table></div>
 {selected.status==='pending'&&can('approvals.review')&&selected.requestedBy!==user.id?<form onSubmit={review} className="mt-6 space-y-4"><Field label="Decision"><select value={decision} onChange={e=>setDecision(e.target.value)}><option value="approved">Approve changes</option><option value="rejected">Reject request</option></select></Field><Field label="Review comments" required><textarea required minLength={3} maxLength={2000} rows={3} value={comments} onChange={e=>setComments(e.target.value)} placeholder="Explain your decision for the audit trail…"/></Field>{error&&<p role="alert" className="text-xs text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={()=>setSelected(null)}>Close</button><Submit busy={busy}>Confirm decision</Submit></div></form>:<p className="mt-5 rounded-lg bg-amber-50 p-3 text-xs leading-5 text-amber-800">{selected.status==='pending'?'This request requires an independent authorized reviewer.':`Review comments: ${selected.reviewComments||'No comments recorded.'}`}</p>}
 </Modal>}</>
}

