import {useState} from 'react'
import {Link} from 'react-router-dom'
import {Package,ArrowDownLeft,ArrowUpRight,Wallet,Plus,ChevronRight,CalendarDays,Warehouse,ClipboardCheck,ArrowRight,AlertTriangle,Truck,RefreshCw} from 'lucide-react'
import {AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,BarChart,Bar} from 'recharts'
import {useApp,useData} from '../lib/context'
import {money,number,date,human} from '../lib/api'
import {PageHeader,Skeleton,ErrorState,Empty,Badge} from '../components/ui'
import MovementForm from '../components/MovementForm'
export default function Dashboard(){
 const {user,can,pending,online}=useApp(),[location,setLocation]=useState(''),[movement,setMovement]=useState(null)
 const query=useData('/dashboard',location?{locationId:location}:{}),locations=useData('/locations',{limit:200},can('locations.read'))
 if(query.isPending)return <Skeleton/>;if(query.error)return <ErrorState error={query.error} retry={query.refetch}/>
 const d=query.data,role=user.roles[0],finance=can('finance.read'),accountant=role==='Accountant',staff=role==='Staff',distributor=role==='Distributor'&&!can('inventory.read')
 const titles={CEO:'Company overview',Admin:'Operations overview',Accountant:'Financial overview',Staff:'Warehouse overview',Distributor:'Distribution overview'}
 const stats=distributor?[[Truck,'Allocated units',number(d.data?.filter(r=>r.type==='distributor_allocation').reduce((n,r)=>n+Number(r.quantity),0)),'Your distribution history'],[RefreshCw,'Returned units',number(d.data?.filter(r=>r.type==='distributor_return').reduce((n,r)=>n+Number(r.quantity),0)),'Recorded returns']]:accountant?[[Wallet,'Approved expenses',money(d.expenses),'Last 30 days'],[ClipboardCheck,'Pending requests',number(d.pending),'Awaiting a decision'],[Warehouse,'Assigned warehouses',number(d.warehouseCount),'Across your locations']]:[[Package,'Total inventory',number(d.totalInventory),'Units across your warehouses'],[ArrowDownLeft,'Incoming stock',number(d.incoming),'Units received · last 30 days'],[ArrowUpRight,'Outgoing stock',number(d.outgoing),'Units dispatched · last 30 days'],finance?[Wallet,'Approved expenses',money(d.expenses),'Last 30 days']:[RefreshCw,'Pending sync',number(pending),online?'Device is connected':'Saved on this device']]
 const trendMap={};for(const row of d.trend||[]){const key=String(row.date).slice(0,10);trendMap[key]??={date:key,incoming:0,outgoing:0};if(row.type==='incoming')trendMap[key].incoming+=Number(row.quantity);if(['outgoing','distributor_allocation'].includes(row.type))trendMap[key].outgoing+=Number(row.quantity)}
 const chartData=accountant?(d.expenseTrend||[]).map(r=>({date:r.expenseDate,amount:Number(r.amount)})):Object.values(trendMap)
 return <><PageHeader eyebrow={user.organizationWide?'COMPANY WORKSPACE':'YOUR WORKSPACE'} title={titles[role]||'Workspace overview'} description={`Welcome back, ${user.name.split(' ')[0]}. Here’s what’s happening across your ${staff?'warehouse':'business'}.`}><div className="btn-secondary"><CalendarDays size={14}/>{date(new Date())}</div>{can('inventory.write')&&<button className="btn" onClick={()=>setMovement('incoming')}><Plus size={16}/>Record goods</button>}</PageHeader>
  <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs"><span className="h-1.5 w-1.5 rounded-full bg-brand-600"/><span className="font-medium text-slate-600">{user.organizationWide?'Company-wide visibility':'Your assigned operations'}</span><span className="text-slate-300">|</span><span className="text-slate-400">Live workspace data</span></div>{can('locations.read')&&<select aria-label="Filter dashboard by location" className="w-auto min-w-44 py-2 text-xs" value={location} onChange={e=>setLocation(e.target.value)}><option value="">All permitted locations</option>{locations.data?.data.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select>}</div>
  <div className={`mb-6 grid gap-4 sm:grid-cols-2 ${stats.length===4?'xl:grid-cols-4':'xl:grid-cols-3'}`}>{stats.map(([Icon,label,value,detail],i)=><div key={label} className="card p-5"><div className="flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><span className={`rounded-lg p-2 ${['bg-brand-50 text-brand-600','bg-blue-50 text-blue-500','bg-violet-50 text-violet-500','bg-orange-50 text-orange-500'][i]}`}><Icon size={18} strokeWidth={1.7}/></span></div><p className="mt-3 text-[29px] font-semibold tracking-[-1px] text-slate-900">{value}</p><p className="mt-2 text-[11px] text-slate-400">{detail}</p></div>)}</div>
  {distributor?<div className="card"><div className="border-b border-slate-100 p-5 font-semibold">Your distribution activity</div>{d.data?.length?<div className="divide-y divide-slate-100">{d.data.map(r=><div key={r.id} className="flex items-center justify-between p-5"><div><p className="font-medium">{r.product?.name}</p><p className="mt-1 text-xs text-slate-400">{r.number} · {date(r.occurredAt)}</p></div><div className="text-right"><p className="mb-1 font-semibold">{number(r.quantity)} units</p><Badge value={r.type}/></div></div>)}</div>:<Empty title="No allocations yet" description="Your assigned stock and delivery information will appear here."/>}</div>:<>
  <div className="mb-6 grid gap-6 xl:grid-cols-[1.8fr_1fr]"><section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="text-sm font-semibold">{accountant?'Expense trends':'Stock movement'}</h2><p className="mt-1 text-[11px] text-slate-400">{accountant?'Approved operational spending':'Incoming and outgoing stock over time'}</p></div><span className="rounded-md border border-slate-200 px-3 py-1.5 text-[11px] text-slate-500">Last 30 days</span></div>{chartData.length?<div className="h-[260px] px-3 pb-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{top:15,right:20,left:0,bottom:0}}><defs><linearGradient id="stockFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#23826b" stopOpacity={.18}/><stop offset="100%" stopColor="#23826b" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#edf1f5"/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} tick={{fontSize:10,fill:'#94a3b8'}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10,fill:'#94a3b8'}} axisLine={false} tickLine={false}/><Tooltip formatter={value=>accountant?money(value):number(value)} contentStyle={{borderRadius:10,border:'1px solid #e2e8f0',fontSize:12}}/><Area type="monotone" name={accountant?'Expenses':'Incoming'} dataKey={accountant?'amount':'incoming'} stroke="#23826b" strokeWidth={2.5} fill="url(#stockFill)"/>{!accountant&&<Area type="monotone" name="Outgoing" dataKey="outgoing" stroke="#e9a360" strokeWidth={2} fill="transparent"/>}</AreaChart></ResponsiveContainer></div>:<Empty title={accountant?'Your spending story starts here':'Ready for your first stock movement'} description="As transactions are recorded, this chart will show actual activity across your locations."/>}<div className="flex justify-center gap-5 border-t border-slate-100 py-3 text-[10px] text-slate-500"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-brand-600"/>{accountant?'Approved expenses':'Incoming stock'}</span>{!accountant&&<span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-orange-300"/>Outgoing stock</span>}</div></section>
  <section className="card flex flex-col"><div className="p-5"><h2 className="text-sm font-semibold">{accountant?'Financial controls':'Operations at a glance'}</h2><p className="mt-1 text-[11px] text-slate-400">The details that keep your business moving</p></div><div className="space-y-1 px-5">{[[Warehouse,'Warehouses',number(d.warehouseCount),'/warehouses'],[ClipboardCheck,'Pending approvals',number(d.pending),'/approvals'],[Truck,'Distributed units',number(d.distribution),'/movements'],...(finance?[[Wallet,'Current stock value',money(d.stockValue),'/reports']]:[])].filter((_,i)=>!accountant||i!==2).map(([Icon,label,value,path])=><Link to={path} key={label} className="flex items-center gap-3 border-b border-slate-100 py-4 last:border-0"><span className="rounded-lg bg-slate-50 p-2.5 text-slate-400"><Icon size={17}/></span><span className="flex-1 text-xs text-slate-500">{label}</span><strong className="text-sm font-semibold">{value}</strong><ChevronRight size={13} className="text-slate-300"/></Link>)}</div><div className="m-5 mt-auto rounded-lg bg-brand-50 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-brand-700"><ClipboardCheck size={15}/>Every action, accounted for</div><p className="mt-2 text-[11px] leading-5 text-brand-700/70">Stock movements and protected changes are recorded in your company’s audit trail.</p></div></section></div>
  {!accountant&&<div className="mb-6 grid gap-6 xl:grid-cols-[1.8fr_1fr]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="text-sm font-semibold">Recent activity</h2><p className="mt-1 text-[11px] text-slate-400">Latest movements across your warehouses</p></div><Link className="flex items-center gap-1 text-xs font-medium text-brand-700" to="/movements">View all <ArrowRight size={13}/></Link></div>{d.recent?.length?<div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Product / Reference</th><th>Warehouse</th><th>Quantity</th><th>Status</th></tr></thead><tbody>{d.recent.map(r=><tr key={r.id}><td><p className="font-medium text-slate-700">{r.product?.name}</p><p className="mt-1 text-[10px] text-slate-400">{r.number}</p></td><td className="text-slate-500">{r.warehouse?.name}</td><td><span className={r.type==='incoming'?'text-emerald-600':'text-slate-600'}>{r.type==='incoming'?'+':'−'}{number(r.quantity)}</span><p className="mt-1 text-[10px] capitalize text-slate-400">{human(r.type)}</p></td><td><Badge value={r.status}/></td></tr>)}</tbody></table></div>:<Empty title="No activity recorded" description="Receive goods or record an outgoing delivery to get started." action={can('inventory.write')&&<button className="btn-secondary" onClick={()=>setMovement('incoming')}><Plus size={14}/>Receive goods</button>}/>}</section><section className="card"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="text-sm font-semibold">Stock alerts</h2><p className="mt-1 text-[11px] text-slate-400">Products that need your attention</p></div><span className="rounded-md bg-amber-50 px-2 py-1 text-xs text-amber-700">{d.lowStock?.length||0}</span></div>{d.lowStock?.length?<div className="divide-y divide-slate-100 px-5">{d.lowStock.map(s=><div key={s.id} className="flex items-center gap-3 py-4"><span className="rounded-lg bg-amber-50 p-2 text-amber-600"><AlertTriangle size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{s.name}</p><p className="mt-1 text-[10px] text-slate-400">{s.warehouse}</p></div><div className="text-right"><p className="text-xs font-semibold text-amber-700">{number(s.available)} left</p><p className="mt-1 text-[10px] text-slate-400">Min. {number(s.minimum)}</p></div></div>)}</div>:<Empty title="No low-stock alerts" description="Products below their configured minimum stock level will appear here."/>}</section></div>}
  {!!d.warehouseComparison?.length&&!accountant&&<section className="card p-5"><h2 className="text-sm font-semibold">Warehouse comparison</h2><p className="mt-1 text-[11px] text-slate-400">Current stock held at each warehouse</p><div className="mt-5 h-56"><ResponsiveContainer width="100%" height="100%"><BarChart data={d.warehouseComparison}><CartesianGrid vertical={false} stroke="#f1f5f9"/><XAxis dataKey="name" tick={{fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="quantity" name="Units" fill="#2b806b" radius={[4,4,0,0]} maxBarSize={44}/></BarChart></ResponsiveContainer></div></section>}
 </>}{movement&&<MovementForm initialType={movement} onClose={()=>setMovement(null)}/>}</>
}
