import {useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {Truck,PackageCheck} from 'lucide-react'
import {useApp,useData} from '../lib/context'
import {api,message,date,number,human} from '../lib/api'
import {PageHeader,Table,Skeleton,ErrorState,Badge,Modal} from '../components/ui'
export default function Distribution(){
 const {notify}=useApp(),client=useQueryClient(),query=useData('/distribution'),[status,setStatus]=useState(''),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function receive(){setBusy(true);try{await api.post(`/distribution/${selected.id}/receive`);await client.invalidateQueries();notify('Delivery receipt confirmed.');setSelected(null)}catch(err){setError(message(err))}finally{setBusy(false)}}
 if(query.isPending)return <Skeleton/>;if(query.error)return <ErrorState error={query.error} retry={query.refetch}/>
 const rows=query.data.data.filter(r=>!status||r.status===status)
 return <><PageHeader eyebrow="DISTRIBUTOR WORKSPACE" title="My distribution" description="Your allocated stock, delivery information, and transaction history."/><div className="mb-6 grid gap-4 sm:grid-cols-2"><div className="card p-5"><Truck className="mb-3 text-brand-600" size={22}/><p className="text-xs text-slate-500">Awaiting receipt confirmation</p><p className="mt-3 text-3xl font-semibold">{query.data.data.filter(r=>r.type==='distributor_allocation'&&r.status==='confirmed').length}</p></div><div className="card p-5"><PackageCheck className="mb-3 text-brand-600" size={22}/><p className="text-xs text-slate-500">Completed deliveries</p><p className="mt-3 text-3xl font-semibold">{query.data.data.filter(r=>r.status==='delivered').length}</p></div></div><select aria-label="Filter deliveries" className="mb-4 w-auto" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All transactions</option><option value="confirmed">Awaiting confirmation</option><option value="delivered">Completed deliveries</option></select><Table rows={rows} total={rows.length} limit={200} columns={[{key:'number',label:'Reference'},{key:'product',label:'Product',render:r=>r.product?.name},{key:'quantity',label:'Quantity',render:r=>`${number(r.quantity)} ${r.product?.unit||''}`},{key:'type',label:'Type',render:r=>human(r.type)},{key:'occurredAt',label:'Date',render:r=>date(r.occurredAt)},{key:'status',label:'Status',render:r=><Badge value={r.status}/>},{key:'action',label:'',render:r=><button className="text-xs font-medium text-brand-700" onClick={()=>{setSelected(r);setError('')}}>View delivery</button>}]} emptyTitle="No distribution transactions yet"/>{selected&&<Modal title={selected.number} onClose={()=>setSelected(null)}><p className="mb-4 text-lg font-semibold">{selected.product?.name} · {number(selected.quantity)} {selected.product?.unit}</p><p className="mb-3 text-sm text-slate-500">{selected.delivery||'No additional delivery instructions.'}</p><p className="text-xs text-slate-400">External reference: {selected.reference||'—'}</p>{selected.type==='distributor_allocation'&&selected.status==='confirmed'&&<div className="mt-6 border-t border-slate-100 pt-5"><p className="mb-4 text-sm text-slate-600">Confirm only after you have received and verified this stock. The confirmation will be recorded in the audit trail.</p>{error&&<p className="mb-3 text-xs text-red-600">{error}</p>}<button className="btn" disabled={busy} onClick={receive}>Confirm goods received</button></div>}</Modal>}</>
}
