import {useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {useApp,useData} from '../lib/context'
import {api,message,human} from '../lib/api'
import {PageHeader,Field,Submit,Modal,Table,Skeleton,ErrorState} from '../components/ui'
const cash=v=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',minimumFractionDigits:2}).format(Number(v||0))
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Lagos'})
const kinds=['customer_payment','expense_payment','other_income','capital','loan_received','supplier_payment','loan_repayment','owner_withdrawal']
export default function Finance(){
 const {can,online,notify}=useApp(),client=useQueryClient()
 const [filters,setFilters]=useState({from:today().slice(0,7)+'-01',to:today()}),[tab,setTab]=useState('entries'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[modal,setModal]=useState(null)
 const query=useData('/finance',filters),locations=useData('/locations',{limit:200})
 if(query.isPending)return <Skeleton/>
 if(query.error)return <ErrorState error={query.error} retry={query.refetch}/>
 const d=query.data,t=d.totals,rows=(d[tab]||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(search.toLowerCase()))
 const columns=tab==='entries'?[{key:'entryDate',label:'Date'},{key:'number',label:'Reference'},{key:'kind',label:'Purpose',render:r=>human(r.kind)},{key:'accountId',label:'Account',render:r=>d.accounts.find(a=>a.id===r.accountId)?.name},{key:'description',label:'Description'},{key:'amount',label:'Amount',render:r=><span className={r.direction==='in'?'text-emerald-700':'text-red-700'}>{r.direction==='in'?'+':'−'}{cash(r.amount)}</span>}]:tab==='sales'?[{key:'number',label:'Sale'},{key:'customer',label:'Customer'},{key:'saleDate',label:'Date'},{key:'revenue',label:'Revenue',render:r=>cash(r.revenue)},{key:'costOfGoods',label:'Goods cost',render:r=>cash(r.costOfGoods)},{key:'outstanding',label:'Unpaid',render:r=>cash(r.outstanding)}]:tab==='expenses'?[{key:'number',label:'Expense'},{key:'description',label:'Description'},{key:'amount',label:'Approved',render:r=>cash(r.amount)},{key:'outstanding',label:'Unpaid',render:r=>cash(r.outstanding)}]:[{key:'name',label:'Account'},{key:'openingBalance',label:'Opening balance',render:r=>cash(r.openingBalance)},{key:'balance',label:'Current balance',render:r=>cash(r.balance)}]
 function exportCsv(){const escape=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const csv=[columns.map(c=>escape(c.label)).join(','),...rows.map(r=>columns.map(c=>escape(r[c.key])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`viva-finance-${tab}-${today()}.csv`;a.click();URL.revokeObjectURL(url)}
 return <><PageHeader eyebrow="BUSINESS FINANCE" title="Money & profit" description="Cash movement, sales performance and unpaid balances in Nigerian naira.">{can('finance.write')&&<><button className="btn-secondary" disabled={!online} onClick={()=>setModal('accounts')}>Add account</button><button className="btn-secondary" disabled={!online} onClick={()=>setModal('sales')}>Record sale</button><button className="btn" disabled={!online} onClick={()=>setModal('cash')}>Record money</button></>}</PageHeader>
 <div className="card mb-6 flex flex-wrap items-end gap-4 p-4"><Field label="From"><input type="date" value={filters.from} max={filters.to} onChange={e=>setFilters({...filters,from:e.target.value})}/></Field><Field label="To"><input type="date" value={filters.to} max={today()} onChange={e=>setFilters({...filters,to:e.target.value})}/></Field><Field label="Location"><select value={filters.locationId||''} onChange={e=>{const next={...filters};if(e.target.value)next.locationId=e.target.value;else delete next.locationId;setFilters(next)}}><option value="">All permitted locations</option>{locations.data?.data.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></Field><p className="text-xs text-slate-500">Dates filter cash movements and profit. Outstanding balances include all dates.</p></div>
 <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Money in',t.cashIn],['Money out',t.cashOut],['Net cash movement',t.netCash],['Operating profit',t.operatingProfit]].map(([label,value])=><div className="card p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className={`mt-3 text-2xl font-semibold ${Number(value)<0?'text-red-700':'text-slate-900'}`}>{cash(value)}</p><p className="mt-2 text-xs text-slate-400">Selected period</p></div>)}</div>
 <div className="mb-6 grid gap-6 lg:grid-cols-2"><section className="card p-5"><h2 className="font-semibold">Profit breakdown</h2><dl className="mt-4 space-y-3 text-sm">{[['Sales revenue',t.revenue],['Less: cost of goods sold',t.costOfGoods],['Gross profit',t.grossProfit],['Less: approved expenses',t.expenses],['Plus: other operating income',t.otherIncome],['Operating profit / loss',t.operatingProfit]].map(([label,value])=><div className="flex justify-between gap-4 border-b border-slate-100 pb-2" key={label}><dt>{label}</dt><dd className="font-medium">{cash(value)}</dd></div>)}</dl></section><section className="card p-5"><h2 className="font-semibold">Outstanding balances</h2><p className="mt-4 text-sm text-slate-500">Customers owe</p><p className="mt-1 text-2xl font-semibold">{cash(d.sales.reduce((v,s)=>v+Number(s.outstanding),0))}</p><p className="mt-4 text-sm text-slate-500">Approved expenses still unpaid</p><p className="mt-1 text-2xl font-semibold">{cash(d.expenses.reduce((v,e)=>v+Number(e.outstanding),0))}</p><p className="mt-5 text-xs leading-6 text-slate-500">Profit includes credit sales and approved expenses. Capital and loan receipts are excluded from profit. Supplier payments are separate: goods costs are recognized through sales. Figures exclude tax calculations.</p></section></div>
 <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{[['entries','Cash movements'],['sales','Sales & receivables'],['expenses','Expense payments'],['accounts','Accounts']].map(([key,label])=><button key={key} className={tab===key?'btn':'btn-secondary'} onClick={()=>{setTab(key);setPage(1)}}>{label}</button>)}</div><button className="btn-secondary" onClick={exportCsv}>Export CSV</button></div><input aria-label="Search finance records" placeholder="Search records…" className="mb-4 max-w-sm" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/><Table columns={columns} rows={rows.slice((page-1)*25,page*25)} total={rows.length} page={page} onPage={setPage}/>
 {modal&&<FinanceForm type={modal} data={d} locations={locations.data?.data||[]} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);client.invalidateQueries();notify('Financial record saved.')}}/>}</>
}
function FinanceForm({type,data,locations,onClose,onSaved}){
 const [form,setForm]=useState(type==='accounts'?{openingBalance:'0'}:type==='sales'?{saleDate:today()}:{kind:'customer_payment',entryDate:today(),operationId:crypto.randomUUID()}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const dispatches=useData('/finance/dispatches',{},type==='sales')
 const put=(key,value)=>setForm({...form,[key]:value})
 const input=(key,label,kind='text',extra={})=><Field label={label} required><input required type={kind} value={form[key]??''} onChange={e=>put(key,e.target.value)} {...extra}/></Field>
 const select=(key,label,rows,getLabel)=><Field label={label} required><select required value={form[key]||''} onChange={e=>put(key,e.target.value)}><option value="">Select…</option>{rows.map(r=><option key={r.id} value={r.id}>{getLabel(r)}</option>)}</select></Field>
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await api.post('/finance/'+type,form);onSaved()}catch(err){setError(message(err))}finally{setBusy(false)}}
 const account=data.accounts.find(a=>a.id===form.accountId)
 return <Modal title={type==='accounts'?'Add cash or bank account':type==='sales'?'Record sale from dispatch':'Record money received or paid'} onClose={onClose}><form onSubmit={save} className="space-y-4">{type==='accounts'?<>{input('name','Account name')}{select('locationId','Location',locations,r=>r.name)}{input('openingBalance','Opening balance (NGN)','number',{min:0,step:'.01'})}<p className="text-xs text-slate-500">Opening balance is money already held before recording transactions. It does not increase profit or cash receipts.</p></>:type==='sales'?<>{dispatches.error&&<ErrorState error={dispatches.error} retry={dispatches.refetch}/>}<p className="text-sm text-slate-500">Choose goods already dispatched. This records the sale without deducting stock again. Each dispatch can have one sale.</p>{select('movementId','Unbilled dispatch',dispatches.data||[],r=>`${r.number} · ${r.quantity} units · ${r.counterparty||'No customer'}`)}{input('customer','Customer / distributor')}{input('saleDate','Sale date','date',{max:today()})}{input('unitPrice','Selling price per unit, excluding tax (NGN)','number',{min:0,step:'.01'})}{input('unitCost','Verified cost per unit (NGN)','number',{min:0,step:'.01'})}<p className="text-xs text-slate-500">Enter the cost of the dispatched goods. This cost is saved with the sale, preserving historical profit when catalog prices change.</p></>:<>{select('accountId','Cash / bank account',data.accounts,r=>`${r.name} · ${cash(r.balance)}`)}<Field label="Purpose"><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value,saleId:undefined,expenseId:undefined})}>{kinds.map(k=><option key={k} value={k}>{human(k)}</option>)}</select></Field>{form.kind==='customer_payment'&&select('saleId','Sale to receive payment for',data.sales.filter(s=>Number(s.outstanding)>0&&s.locationId===account?.locationId),r=>`${r.number} · ${r.customer} · owes ${cash(r.outstanding)}`)}{form.kind==='expense_payment'&&select('expenseId','Approved expense to pay',data.expenses.filter(s=>Number(s.outstanding)>0&&s.locationId===account?.locationId),r=>`${r.number} · ${r.description} · unpaid ${cash(r.outstanding)}`)}{input('amount','Amount (NGN)','number',{min:'.01',step:'.01'})}{input('entryDate','Payment date','date',{max:today()})}{input('description','Description')}<Field label="Bank / receipt reference"><input value={form.reference||''} onChange={e=>put('reference',e.target.value)}/></Field></>}
 <p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Check details before posting. Financial entries are permanent audit records; editing and reversals are not available in this release.</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><Submit busy={busy}>Post record</Submit></div></form></Modal>
}
