import {useState} from 'react'
import {useSearchParams} from 'react-router-dom'
import {Download,FileBarChart,ArrowRight} from 'lucide-react'
import {useApp,useData} from '../lib/context'
import {api,message,human} from '../lib/api'
import {PageHeader,Field,Table,ErrorState,Skeleton} from '../components/ui'
const types=[['inventory','Inventory report','inventory.read'],['incoming','Incoming goods','inventory.read'],['outgoing','Outgoing goods','inventory.read'],['warehouses','Warehouse report','locations.read'],['locations','Branch report','locations.read'],['expenses','Expense report','finance.read'],['distributors','Distributor report','distributors.read'],['movements','Stock movement report','inventory.read'],['damaged','Damaged goods','inventory.read'],['audit','Audit report','audit.read'],['approvals','Approval report','approvals.read']]
export default function Reports(){
 const {can,notify}=useApp(),[search]=useSearchParams(),available=types.filter(t=>can(t[2])),[type,setType]=useState(available.some(t=>t[0]===search.get('type'))?search.get('type'):available[0]?.[0]||'inventory'),[filters,setFilters]=useState({from:'',to:'',locationId:'',warehouseId:'',productId:'',status:''}),[applied,setApplied]=useState(null),[busy,setBusy]=useState(false),[page,setPage]=useState(1)
 const locations=useData('/locations',{limit:200},can('locations.read')),warehouses=useData('/warehouses',{limit:200},can('locations.read')),products=useData('/products',{limit:200},can('products.read'))
 const query=useData(`/reports/${applied?.type||type}`,applied?.params||{},!!applied)
 const params=()=>Object.fromEntries(Object.entries(filters).filter(([,v])=>v))
 async function download(){setBusy(true);try{const result=await api.get(`/reports/${type}`,{params:{...params(),format:'csv'},responseType:'blob'});const url=URL.createObjectURL(result.data),link=document.createElement('a');link.href=url;link.download=`viva-${type}.csv`;link.click();URL.revokeObjectURL(url);notify('Report exported.')}catch(e){notify(message(e),'error')}finally{setBusy(false)}}
 const rows=query.data?.data||[],keys=rows.length?Object.keys(rows[0]).filter(k=>!['deletedAt','updatedAt'].includes(k)).slice(0,9):[]
 return <><PageHeader eyebrow="BUSINESS INTELLIGENCE" title="Reports" description="Turn operational records into a clear picture of your business."><button className="btn-secondary" onClick={download} disabled={busy}><Download size={15}/>Export CSV</button></PageHeader><div className="grid gap-6 xl:grid-cols-[240px_1fr]"><div className="card h-fit p-2">{available.map(([key,label])=><button key={key} onClick={()=>{setType(key);setApplied(null)}} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-xs ${type===key?'bg-brand-50 font-semibold text-brand-700':'text-slate-500 hover:bg-slate-50'}`}><FileBarChart size={16}/>{label}</button>)}</div><div><div className="card mb-5 p-5"><h2 className="mb-5 text-base font-semibold">{available.find(t=>t[0]===type)?.[1]}</h2><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[['from','From date'],['to','To date']].map(([key,label])=><Field key={key} label={label}><input type="date" value={filters[key]} onChange={e=>setFilters(f=>({...f,[key]:e.target.value}))}/></Field>)}{[['locationId','Location',locations],['warehouseId','Warehouse',warehouses],['productId','Product',products]].map(([key,label,data])=><Field key={key} label={label}><select value={filters[key]} onChange={e=>setFilters(f=>({...f,[key]:e.target.value}))}><option value="">All permitted {label.toLowerCase()}s</option>{data.data?.data?.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>)}<Field label="Status"><select value={filters.status} onChange={e=>setFilters(f=>({...f,status:e.target.value}))}><option value="">All statuses</option>{['pending','approved','confirmed','rejected','received','cancelled'].map(s=><option key={s}>{s}</option>)}</select></Field></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-[11px] text-slate-400">Exports include up to 10,000 matching records. Narrow dates for larger datasets.</p><button className="btn" onClick={()=>{setApplied({type,params:params()});setPage(1)}}>Generate report <ArrowRight size={15}/></button></div></div>{applied&&(query.isPending?<Skeleton/>:query.error?<ErrorState error={query.error} retry={query.refetch}/>:<Table rows={rows.slice((page-1)*25,page*25)} columns={keys.map(key=>({key,label:human(key),render:r=>typeof r[key]==='object'?JSON.stringify(r[key]):String(r[key]??'—')}))} total={rows.length} page={page} onPage={setPage} emptyTitle="No records match these filters"/>)}</div></div></>
}
