import {useState} from 'react'
import {Link} from 'react-router-dom'
import {useQueryClient} from '@tanstack/react-query'
import {Plus,Search,SlidersHorizontal,ArrowUpRight,Download} from 'lucide-react'
import {modules} from '../lib/modules'
import {api,message,human} from '../lib/api'
import {useApp,useData} from '../lib/context'
import {PageHeader,Skeleton,ErrorState,Table,Badge,Modal,Field,Submit} from '../components/ui'
import RecordForm,{ReferenceInput} from '../components/RecordForm'
import MovementForm from '../components/MovementForm'
export default function Resources({module}){
 const config=modules[module],{can,notify,online}=useApp(),client=useQueryClient()
 const [q,setQ]=useState(''),[page,setPage]=useState(1),[status,setStatus]=useState(''),[filters,setFilters]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[locationId,setLocationId]=useState(''),[warehouseId,setWarehouseId]=useState(''),[create,setCreate]=useState(false),[selected,setSelected]=useState(null),[edit,setEdit]=useState(null),[action,setAction]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const query=useData(`/${module}`,{page,limit:25,...(q?{q}:{}),...(status?{status}:{}),...(from?{from}:{}),...(to?{to}:{}),...(locationId?{locationId}:{}),...(warehouseId?{warehouseId}:{})})
 const locations=useData('/locations',{limit:200},can('locations.read')),warehouses=useData('/warehouses',{limit:200},can('locations.read')),products=useData('/products',{limit:200},module==='transfers')
 const names=Object.fromEntries([...(locations.data?.data||[]),...(warehouses.data?.data||[]),...(products.data?.data||[])].map(x=>[x.id,x.name]))
 let columns=config.columns.filter(c=>can('finance.read')||!['costPrice','sellingPrice'].includes(c.key)).map(c=>c.badge?{...c,render:r=><Badge value={c.key==='active'?(r.active?'active':'inactive'):r[c.key]}/>}:(['locationId','productId','sourceWarehouseId','destinationWarehouseId'].includes(c.key)?{...c,render:r=>names[r[c.key]]||r[c.key]?.slice(0,8)}:c))
 columns=[...columns,{key:'actions',label:'',render:r=><button aria-label={`View record ${r.name||r.number||r.id}`} className="text-xs font-medium text-brand-700 hover:underline" onClick={()=>{setSelected(r);setError('')}}>View</button>}]
 async function transferAction(e){e.preventDefault();setBusy(true);setError('');try{await api.post(`/transfers/${selected.id}/action`,{action});await client.invalidateQueries();notify('Transfer updated.');setSelected(null);setAction('')}catch(err){setError(message(err))}finally{setBusy(false)}}
 return <><PageHeader eyebrow="OPERATIONS" title={config.title} description={config.description}>{['products','expenses'].includes(module)&&<Link className="btn-secondary" to={module==='products'?'/product-categories':'/expense-categories'}>Categories</Link>}{module==='users'&&<Link className="btn-secondary" to="/roles">Roles & permissions</Link>}{can(config.write)&&<button className="btn" disabled={!online&&!config.movement} onClick={()=>setCreate(true)}><Plus size={16}/>{config.movement?'Record movement':`New ${config.singular}`}</button>}</PageHeader>
  <div className="card mb-5 p-4"><div className="flex flex-wrap items-center gap-3"><div className="relative min-w-48 flex-1 sm:max-w-sm"><Search size={16} className="absolute left-3 top-3 text-slate-400"/><input className="pl-9" aria-label="Search records" placeholder={`Search ${config.title.toLowerCase()}…`} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div>{['incoming','outgoing','movements','expenses','transfers'].includes(module)&&<select aria-label="Filter by status" className="w-auto" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option>{['pending','approved','confirmed','in_transit','received','rejected','cancelled'].map(s=><option key={s}>{s}</option>)}</select>}<button className="btn-secondary ml-auto" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={15}/>Filters</button>{can('reports.read')&&<Link to={`/reports?type=${module==='inventory'?'inventory':module}`} className="icon-btn" aria-label="Open reports"><Download size={17}/></Link>}</div>{filters&&<div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-4"><Field label="From"><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></Field><Field label="To"><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></Field>{can('locations.read')&&<><Field label="Location"><select value={locationId} onChange={e=>{setLocationId(e.target.value);setPage(1)}}><option value="">All locations</option>{locations.data?.data?.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Field label="Warehouse"><select value={warehouseId} onChange={e=>{setWarehouseId(e.target.value);setPage(1)}}><option value="">All warehouses</option>{warehouses.data?.data?.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field></>}</div>}</div>
  {query.isPending?<Skeleton/>:query.error?<ErrorState error={query.error} retry={query.refetch}/>:<Table columns={columns} rows={query.data.data} total={query.data.total} page={page} onPage={setPage} emptyTitle={`No ${config.title.toLowerCase()} found`}/>}
  {create&&(config.movement?<MovementForm initialType={config.movement} onClose={()=>setCreate(false)}/>:<RecordForm module={module} onClose={()=>setCreate(false)}/>)}
  {edit&&<RecordForm module={module} record={edit} onClose={()=>setEdit(null)}/>}
  {selected&&<Modal title={selected.name||selected.number||'Record details'} description={`Record ID: ${selected.id}`} onClose={()=>{setSelected(null);setAction('')}}><dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2">{Object.entries(selected).filter(([k])=>!['id','deletedAt'].includes(k)).map(([key,value])=><div key={key} className={typeof value==='object'&&value?'sm:col-span-2':''}><dt className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-slate-400">{human(key.replace(/([A-Z])/g,' $1'))}</dt><dd className="break-words text-xs leading-6 text-slate-700">{typeof value==='object'&&value?<pre className="max-h-56 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-[11px]">{JSON.stringify(value,null,2)}</pre>:String(value??'—')}</dd></div>)}</dl>
   {['products','locations','warehouses','distributors','expenses','incoming','outgoing','movements'].includes(module)&&can(config.write)&&<div className="mt-6 border-t border-slate-100 pt-5"><button className="btn" onClick={()=>{setEdit(selected);setSelected(null)}}>Request correction <ArrowUpRight size={15}/></button></div>}
   {module==='users'&&can('users.manage')&&<UserAccess user={selected} onSaved={()=>setSelected(null)}/>}
   {module==='transfers'&&<form className="mt-6 space-y-4 border-t border-slate-100 pt-5" onSubmit={transferAction}><Field label="Transfer action"><select required value={action} onChange={e=>setAction(e.target.value)}><option value="">Choose an action</option>{(selected.status==='pending'&&can('approvals.review')?['approve','reject']:selected.status==='approved'&&can('inventory.write')?['release']:selected.status==='in_transit'&&can('inventory.write')?['receive']:[]).map(a=><option key={a} value={a}>{human(a)}</option>)}{['pending','approved'].includes(selected.status)&&<option value="cancel">Cancel transfer</option>}</select></Field><p className="text-xs text-slate-500">Confirming release removes stock from the source. Receipt adds stock at the destination.</p>{error&&<p role="alert" className="text-xs text-red-600">{error}</p>}<Submit busy={busy||!action}>Confirm action</Submit></form>}
  </Modal>}
 </>
}
function UserAccess({user,onSaved}){const [roles,setRoles]=useState(user.roles?.map(r=>r.id)||[]),[locations,setLocations]=useState(user.locations?.map(l=>l.id)||[]),[active,setActive]=useState(user.active),[busy,setBusy]=useState(false),[error,setError]=useState('');const {notify}=useApp(),client=useQueryClient();async function submit(e){e.preventDefault();setBusy(true);try{await api.patch(`/users/${user.id}`,{roleIds:roles,locationIds:locations,active});await client.invalidateQueries();notify('Access updated. Existing sessions revoked.');onSaved()}catch(err){setError(message(err))}finally{setBusy(false)}}return <form className="mt-6 space-y-4 border-t border-slate-100 pt-5" onSubmit={submit}><h3 className="font-semibold">Update access</h3><Field label="Roles"><ReferenceInput field={{name:'roleIds',label:'Roles',source:'roles',required:true}} value={roles} onChange={setRoles}/></Field><Field label="Locations"><ReferenceInput field={{name:'locationIds',label:'Locations',source:'locations'}} value={locations} onChange={setLocations}/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Account active</label>{error&&<p className="text-xs text-red-600">{error}</p>}<Submit busy={busy}>Confirm access changes</Submit></form>}
