import {useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {Plus,ClipboardList,LockKeyhole} from 'lucide-react'
import {useApp,useData} from '../lib/context'
import {api,message,number,date} from '../lib/api'
import {PageHeader,Table,Badge,Modal,Field,Submit,ErrorState,Skeleton} from '../components/ui'
import {ReferenceInput} from '../components/RecordForm'
export default function StockTools(){
 const {can,online,notify}=useApp(),client=useQueryClient(),[tab,setTab]=useState('stock-counts'),[create,setCreate]=useState(false),[selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(1)
 const [form,setForm]=useState({warehouseId:'',productId:'',quantity:'',notes:'',reference:''})
 const query=useData(`/${tab}`),stock=useData('/inventory',{warehouseId:form.warehouseId,productId:form.productId,limit:200},!!form.warehouseId&&!!form.productId),warehouses=useData('/warehouses',{limit:200}),products=useData('/products',{limit:200})
 const names=Object.fromEntries([...(warehouses.data?.data||[]),...(products.data?.data||[])].map(r=>[r.id,r.name]))
 const change=(key,value)=>setForm(f=>({...f,[key]:value}))
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api.post(`/${tab}`,{...form,quantity:Number(form.quantity),expectedVersion:stock.data?.data?.[0]?.version||0});await client.invalidateQueries();notify(tab==='stock-counts'?'Count recorded. Any variance is submitted for approval.':'Stock reserved.');setCreate(false)}catch(err){setError(message(err))}finally{setBusy(false)}}
 async function release(){setBusy(true);setError('');try{await api.post(`/reservations/${selected.id}/release`);await client.invalidateQueries();setSelected(null);notify('Reservation released.')}catch(err){setError(message(err))}finally{setBusy(false)}}
 const rows=query.data?.data||[]
 return <><PageHeader eyebrow="INVENTORY CONTROLS" title="Counts & reservations" description="Reconcile physical stock and protect quantities committed to future dispatches.">{can('inventory.write')&&<button className="btn" disabled={!online} onClick={()=>{setForm({warehouseId:'',productId:'',quantity:'',notes:'',reference:''});setError('');setCreate(true)}}><Plus size={15}/>{tab==='stock-counts'?'Record stock count':'Reserve stock'}</button>}</PageHeader><div className="mb-5 flex gap-3"><button className={tab==='stock-counts'?'btn':'btn-secondary'} onClick={()=>{setTab('stock-counts');setPage(1)}}><ClipboardList size={15}/>Stock counts</button><button className={tab==='reservations'?'btn':'btn-secondary'} onClick={()=>{setTab('reservations');setPage(1)}}><LockKeyhole size={15}/>Reservations</button></div>{query.isPending?<Skeleton/>:query.error?<ErrorState error={query.error} retry={query.refetch}/>:<Table rows={rows.slice((page-1)*25,page*25)} total={rows.length} page={page} onPage={setPage} columns={[{key:'number',label:'Reference'},{key:'productId',label:'Product',render:r=>names[r.productId]||r.productId.slice(0,8)},{key:'warehouseId',label:'Warehouse',render:r=>names[r.warehouseId]||r.warehouseId.slice(0,8)},...(tab==='stock-counts'?[{key:'expectedQuantity',label:'System stock',render:r=>number(r.expectedQuantity)},{key:'countedQuantity',label:'Counted',render:r=>number(r.countedQuantity)},{key:'variance',label:'Variance',render:r=>number(r.variance)}]:[{key:'quantity',label:'Quantity',render:r=>number(r.quantity)},{key:'status',label:'Status',render:r=><Badge value={r.status}/>}]),{key:'createdAt',label:'Recorded',render:r=>date(r.createdAt)},{key:'actions',label:'',render:r=>tab==='reservations'&&r.status==='reserved'&&can('inventory.write')?<button className="text-xs font-medium text-brand-700" onClick={()=>{setSelected(r);setError('')}}>Release</button>:r.approvalId?<span className="text-xs text-amber-700">See approval request</span>:null}]}/>}
 {create&&<Modal title={tab==='stock-counts'?'Record a physical stock count':'Reserve stock'} description="This operation requires a live connection and current stock version." onClose={()=>setCreate(false)}><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{[['warehouseId','Warehouse','warehouses'],['productId','Product','products']].map(([key,label,source])=><Field key={key} label={label} required><ReferenceInput field={{name:key,label,source,required:true}} value={form[key]} onChange={value=>change(key,value)}/></Field>)}<Field label={tab==='stock-counts'?'Counted quantity':'Quantity to reserve'} required><input type="number" min={tab==='stock-counts'?0:0.001} step="0.001" required value={form.quantity} onChange={e=>change('quantity',e.target.value)}/></Field><Field label="External reference"><input maxLength={255} value={form.reference} onChange={e=>change('reference',e.target.value)}/></Field></div><p className="text-xs text-slate-500">On hand: {number(stock.data?.data?.[0]?.quantity)} · Available: {number(stock.data?.data?.[0]?.available)}</p><Field label="Reason / count notes" required><textarea required minLength={5} maxLength={2000} rows={3} value={form.notes} onChange={e=>change('notes',e.target.value)}/></Field>{error&&<p role="alert" className="text-xs text-red-600">{error}</p>}<div className="flex justify-end"><Submit busy={busy||!stock.data}>Confirm {tab==='stock-counts'?'stock count':'reservation'}</Submit></div></form></Modal>}
 {selected&&<Modal title="Release reserved stock?" onClose={()=>setSelected(null)}><p className="text-sm leading-6 text-slate-600">This makes {number(selected.quantity)} units available again. It does not dispatch stock. The release will be recorded in the ledger.</p>{error&&<p className="mt-3 text-xs text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={()=>setSelected(null)}>Keep reservation</button><button className="btn" disabled={busy} onClick={release}>Confirm release</button></div></Modal>}</>
}
