import {useEffect,useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {RefreshCw,Wifi,WifiOff,Download} from 'lucide-react'
import {useApp,useData} from '../lib/context'
import {operations,synchronize} from '../lib/offline'
import {api,date,human,message} from '../lib/api'
import {PageHeader,Table,Badge,Modal,Field,Submit} from '../components/ui'
export default function SyncCenter(){
 const {user,online,can,notify}=useApp(),client=useQueryClient(),[local,setLocal]=useState([]),[busy,setBusy]=useState(false),[tab,setTab]=useState('device'),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[error,setError]=useState('')
 const remote=useData('/sync')
 useEffect(()=>{const refresh=()=>operations(user.id).then(setLocal).catch(e=>setError(message(e)));refresh();window.addEventListener('viva-sync',refresh);return()=>window.removeEventListener('viva-sync',refresh)},[user.id])
 async function sync(){setBusy(true);try{await synchronize(user.id);await client.invalidateQueries();notify('Synchronization attempt complete. Review the status of each operation.')}catch(e){notify(message(e),'error')}finally{setBusy(false)}}
 async function resolve(e){e.preventDefault();setBusy(true);try{await api.post(`/sync/${selected.id}/resolve`,{reason});await client.invalidateQueries();setSelected(null);notify('Conflict review recorded. No stock was overwritten.')}catch(err){setError(message(err))}finally{setBusy(false)}}
 function download(){const blob=new Blob([JSON.stringify(local,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='viva-pending-operations.json';link.click();URL.revokeObjectURL(url)}
 const rows=tab==='device'?local:(remote.data?.data||[]),last=local.filter(o=>o.syncedAt).map(o=>o.syncedAt).sort().at(-1)
 return <><PageHeader eyebrow="WORKSPACE RELIABILITY" title="Sync center" description="Your work is preserved, even when the connection isn’t."><button className="btn-secondary" onClick={download}><Download size={15}/>Export device records</button><button className="btn" disabled={!online||busy} onClick={sync}><RefreshCw size={15} className={busy?'animate-spin':''}/>Synchronize now</button></PageHeader><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Pending',local.filter(o=>o.status==='pending').length],['Synchronized',local.filter(o=>o.status==='synced').length],['Failed',local.filter(o=>o.status==='failed').length],['Conflicts',local.filter(o=>o.status==='conflict').length]].map(([label,value])=><div className="card p-5" key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold">{value}</p><p className="mt-2 text-[10px] text-slate-400">On this device</p></div>)}</div><div className="card mb-5 flex flex-wrap items-center justify-between gap-3 p-4"><div className="flex items-center gap-2 text-xs">{online?<Wifi size={16} className="text-brand-600"/>:<WifiOff size={16} className="text-amber-600"/>}{online?'Connected · automatic retry every 30 seconds':'Offline · records stay on this device'}</div><span className="text-xs text-slate-400">Last synchronized: {last?date(last):'Not yet'}</span></div><div className="mb-4 flex gap-3">{[['device','This device'],['server',can('approvals.review')?'Server operations & conflicts':'My server operations']].map(([key,label])=><button key={key} className={key===tab?'btn':'btn-secondary'} onClick={()=>setTab(key)}>{label}</button>)}</div>{error&&<p role="alert" className="mb-4 text-sm text-red-600">{error}</p>}<Table rows={rows} total={rows.length} limit={rows.length||25} columns={[{key:'id',label:'Operation',render:r=><span className="font-mono text-xs">{(r.operationId||r.id).slice(0,12)}</span>},{key:'type',label:'Type',render:r=>human(r.payload?.type)},{key:'quantity',label:'Quantity',render:r=>r.payload?.quantity},{key:'createdAt',label:'Recorded',render:r=>date(r.payload?.occurredAt||r.createdAt)},{key:'status',label:'Status',render:r=><Badge value={r.status}/>},{key:'error',label:'Details',render:r=><span className="text-xs text-slate-500">{r.error||r.serverRecord?.number||r.result?.number||'—'}</span>},{key:'action',label:'',render:r=>tab==='server'&&r.status==='conflict'&&can('approvals.review')?<button className="text-xs font-medium text-brand-700" onClick={()=>{setSelected(r);setReason('');setError('')}}>Review</button>:null}]} emptyTitle="No synchronization operations"/>
 <div className="mt-5 rounded-lg border border-blue-100 bg-blue-50 p-4 text-xs leading-6 text-blue-900">Conflicts never overwrite server stock. Review the original operation and current inventory, record a resolution, then submit a new movement only if needed. The original operation remains in the history. Keep this device’s browser data until all pending work is reconciled.</div>
 {selected&&<Modal title="Review synchronization conflict" onClose={()=>setSelected(null)}><p className="mb-4 text-sm text-red-600">{selected.error}</p><pre className="max-h-64 overflow-auto rounded-lg bg-slate-50 p-4 text-xs">{JSON.stringify(selected.payload,null,2)}</pre><form className="mt-5 space-y-4" onSubmit={resolve}><Field label="Resolution and reconciliation notes" required><textarea required minLength={5} maxLength={1000} rows={4} value={reason} onChange={e=>setReason(e.target.value)}/></Field><p className="text-xs text-slate-500">This records your review. It does not apply the conflicting movement.</p>{error&&<p role="alert" className="text-xs text-red-600">{error}</p>}<Submit busy={busy}>Record review</Submit></form></Modal>}</>
}

